config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#landing'
  get "garages/index", to: "garages#index"
  get "/how_it_works", to: 'pages#how_it_works'
  resources :users, only: [:edit, :update] do
    resources :bikes, only: [:create, :new]
    member do
      get "dashboard/home", to: "users#home"
      get "dashboard/my_account", to: "users#show"
      get "dashboard/my_garages", to: "users#mygarages"
      get "dashboard/my_bookings", to: "users#mybookings"
      get "dashboard/add_review", to: "users#addareview"
      get "bookings/:id/accept", to: "bookings#accept_request", as: "accept"
      get "bookings/:id/reject", to: "bookings#reject_request", as: "reject"
      get "bookings/:id/cancel_request_by_owner", to: "bookings#cancel_request_by_owner", as: "cancel_request_by_owner"
      get "bookings/:id/cancel_request_by_biker", to: "bookings#cancel_request_by_biker", as: "cancel_request_by_biker"
      delete "bookings/:id/delete_request", to: "bookings#destroy", as: "delete_request"
    end
    resources :garages, except: [:index] do
      member do
        get "card", to: "garages#show_card"
        get "garages-prompt-loggin", to: "garages#show_prompt_loggin"
      end
      resources :reviews, only: [:new, :create]
      resources :bookings, only: [:new, :edit, :create, :update, :show] do
        resources :chats, only: [ :new, :create ]
      end
    end
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end
  mount ActionCable.server => "/cable"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/garage.rb
class Garage < ApplicationRecord
  mount_uploader :profile_image, PhotoUploader
  monetize :price_regular_bike_cents
  monetize :price_large_bike_cents

  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  has_many :feature_presences, dependent: :destroy
  has_many :features, through: :feature_presences
  has_many :image_galleries, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :description, :street_number, :street_address, :city, :country, presence: true
  validates :capacity_reg_bikes, :capacity_large_bikes, presence: true, numericality: { only_integer: true }

  geocoded_by :address
  after_validation :geocode
  # , if: :will_save_change_to_address?

  def address
    street = [street_address, street_number].compact.join(' ')
    [street, city, country].compact.join(', ')
  end

  def capacity_left_regular
    capacity_reg_bikes - self.bookings.where.not(status: ["rejected", "cancelled_by_owner", "cancelled_by_biker", "done"]).select{|booking|  booking.bike.bike_size == "regular" }.count
  end

  def capacity_left_large
    capacity_large_bikes - self.bookings.where.not(status: ["rejected", "cancelled_by_owner", "cancelled_by_biker", "done"]).select{|booking|  booking.bike.bike_size == "cargo" }.count
  end
end

app/controllers/garages_controller.rb
class GaragesController < ApplicationController

  skip_before_action :authenticate_user!, only: [:index, :show, :show_card]

  def index
    @features = Feature.all
    @garages = Garage.all
    @garages = Garage.geocoded #returns garages with coordinates
    @markers = @garages.map do |garage|
      {
        lat: garage.latitude,
        lng: garage.longitude,
        id: garage.id,
        user_id: garage.user_id,
        infoWindow: render_to_string(partial: "info_window", locals: { garage: garage }),
        image_url: helpers.asset_url('/map_marker.png'),
        features: garage.feature_presences.map { |feature_presence| feature_presence.feature.name }
      }
    end
  end

  def show_card
    @garage = Garage.find(params[:id])
    respond_to do |format|
      p format
      format.js
    end
  end

  def new
    @garage = Garage.new
  end

  def create
    @garage = Garage.new(garage_params)
    @garage.user_id = params[:user_id]
    @garage.features <<  params[:garage][:feature_ids].compact.map{|id| Feature.find_by id: id }.compact.flatten
    if @garage.save
      redirect_to user_garage_path(current_user, @garage)
    else
      render :new
    end
  end

  def edit
    @garage = Garage.find(params[:id])
  end

  def update
    @garage = Garage.find(params[:id])
    @garage.update(garage_params)
    @garage.feature_presences.destroy_all
    @garage.features << params[:garage][:feature_ids].compact.map{|id| Feature.find_by id: id }.compact.flatten
    if @garage.save
      redirect_to user_garage_path(current_user, @garage)
    else
      render :new
    end
  end

  def show
    @garage = Garage.find(params[:id])
    @user = User.find(params[:user_id])
    @features = @garage.features
    @booking = Booking.new
    @bike = Bike.new
    @markers = [@garage].map do |garage|
      {
        lat: garage.latitude,
        lng: garage.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { garage: garage }),
        image_url: helpers.asset_url("/map_marker.png")
      }
    end
    @review_average = review_avarage(@garage)
  end

  def show_prompt_loggin
    redirect_to user_garage_path(current_user, params[:id])
  end

  def destroy
    @garage = Garage.find(params[:id])
    @garage.destroy ? (redirect_to request.referrer) : raise
  end

  def garage_params
    params.require(:garage).permit(
                                    :name,
                                    :description,
                                    :street_number,
                                    :street_address,
                                    :city,
                                    :country,
                                    :capacity_reg_bikes,
                                    :capacity_large_bikes,
                                    :price_regular_bike,
                                    :feature_ids,
                                    :price_large_bike,
                                    :profile_image
                                  )
  end

  def review_avarage(garage)
    reviews_rating = []
    garage.bookings.each do |booking|
      booking.reviews.each do |review|
        reviews_rating << review.rating
      end
    end
    return reviews_rating.any? ? (reviews_rating.sum.to_f / reviews_rating.length.to_f).round(0) : 0
  end
end

app/views/garages/_form.html.erb
<div class="row justify-content-center">
  <div class="col-12 col-sm-10 custom-form">

    <% if garage.new_record? %>
      <h2>Register your garage:</h2>
    <% else %>
      <h2>Edit your garage:</h2>
    <% end %>

    <%= simple_form_for [current_user, garage] do |f| %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :street_number %>
      <%= f.input :street_address %>
      <%= f.input :city %>
      <%= f.input :country %>
      <%= f.input :capacity_reg_bikes, label: 'Capacity for regular bikes' %>
      <%= f.input :capacity_large_bikes, label: 'Capacity for large bikes (e.g. cargo bikes)' %>
      <%= f.input :price_regular_bike, label: 'Price for regular bikes'  %>
      <%= f.input :price_large_bike, label: 'Price for large bikes'  %>

      <%= f.association :features,   as: :check_boxes %>

      <%= f.input :profile_image, label: 'Upload a photo of your garage:'  %>
      <%= f.input :profile_image_cache, as: :hidden %>
      <%= f.button :submit, class: "btn btn-flat" %>
    <% end %>

  </div>
</div>

app/views/garages/_info_window.html.erb
<% if user_signed_in? %>
  <%= link_to user_garage_path(current_user, garage), class: 'index-card' do %>
    <div class="index-card-img-top" style="background-image: url(<%= cl_image_path garage.profile_image %>);"></div>
    <div class="index-card-body">
      <h5 class="index-card-title"><%= garage.name %></h5>
      <p class="index-card-text"><%= garage.street_address %>, <%= garage.city %></p>
      <h6 class="price-tag">€<%= garage.price_regular_bike %>/month</h6>
    </div>
  <% end %>
<% else %>
  <%= link_to user_garage_path(garage.user, garage), class: 'index-card' do %>
    <div class="index-card-img-top" style="background-image: url(<%= cl_image_path garage.profile_image %>);"></div>
    <div class="index-card-body">
      <h5 class="index-card-title"><%= garage.name %></h5>
      <p class="index-card-text"><%= garage.street_address %>, <%= garage.city %></p>
      <h6 class="price-tag">€<%= garage.price_regular_bike %>/month</h6>
    </div>
  <% end %>
<% end %>

app/views/garages/_map_card.html.erb
<% if user_signed_in? %>
  <%= link_to user_garage_path(current_user, garage), class: 'index-card grow' do %>
    <div class="index-card-img-top" style="background-image: url(<%= cl_image_path garage.profile_image %>);"></div>
    <div class="index-card-body">
      <h5 class="index-card-title"><%= garage.name %></h5>
      <p class="index-card-text"><%= garage.street_address %>, <%= garage.city %></p>
      <h6 class="price-tag">€<%= garage.price_regular_bike %>/month</h6>
    </div>
  <% end %>
<% else %>
  <%= link_to user_garage_path(garage.user, garage), class: 'index-card grow' do %>
    <div class="index-card-img-top" style="background-image: url(<%= cl_image_path garage.profile_image %>);"></div>
    <div class="index-card-body">
      <h5 class="index-card-title"><%= garage.name %></h5>
      <p class="index-card-text"><%= garage.street_address %>, <%= garage.city %></p>
      <h6 class="price-tag">€<%= garage.price_regular_bike %>/month</h6>
    </div>
  <% end %>
<% end %>

app/views/garages/edit.html.erb
<%= render 'form', garage: @garage %>

app/views/garages/index.html.erb
<div class="search-page-container">
  <div id="search-filter" class="left-sidebar-map">
    <div class="search-garage-features wrap-collabsible">
      <input id="collapsible-feature-list" class="toggle" type="checkbox">
      <label for="collapsible-feature-list" class="lbl-toggle expand filter-toggle"><h3>Filters</h3></label>
      <div class="collapsible-content">
        <div class="content-inner">
          <% @features.each do |feature| %>
            <div class="search-garage-feature">
              <div class="inputGroup">
                <input type="checkbox" class="checkbox" id="<%= feature.name %>" name="<%= feature.name %>" value="<%= feature.name %>">
                <label for="<%= feature.name %>"><%= render inline: feature.icon_image %> <%= feature.name.capitalize %></label>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div
    id="map"
    class="index-map"
    style="width: 100%;
    height: 100%;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>



  <div class="index-cards" id="garage-card-list">
    <% @garages.last(5).each do |garage| %>
      <%= render "map_card", garage: garage %>
    <% end %>
  </div>
</div>

app/views/garages/new.html.erb
<%= render 'form', garage: @garage %>

app/views/garages/show.html.erb
<div
  id="map"
  class="garage-map"
  style="width: 100%;
  height: 300px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>

<div class="container">

  <div class="row">

    <div class="col-12 col-md-7 col-lg-8">
      <div class="garage-show-body">
        <h2><%= @garage.name %></h2>
        <h3><%= @garage.street_number %> <%= @garage.street_address %>, <%= @garage.city %>, <%= @garage.country %></h3>
        <p><%= @garage.description %></p>
      </div>

      <div class="garage-show-card spots-available">
        <i class="fas fa-warehouse"></i>
        <h4>Spots available :</h4>
        <p><%= @garage.capacity_left_regular < 0 ? 0 : @garage.capacity_left_regular %> regular bikes</p>
        <p><%= @garage.capacity_left_large < 0 ? 0 : @garage.capacity_left_large %> large bikes</p>
      </div>

      <div class="garage-features">
        <% @features.each do |feature| %>
          <div class="garage-feature">
            <p class="feature-icon"><%= render inline: feature.icon_image %></p>
            <p><%= feature.name.capitalize %></p>
          </div>
        <% end %>
      </div>

      <div class= "garage-show-photo">
        <%= cl_image_tag @garage.profile_image, width: 400, height: 267, crop: :fill %>
      </div>

      <% if @review_average > 0 %>
        <div class="reviews-container">
          <h4>Reviews (avg:
              <% @review_average.times do %>
                <i class="fas fa-star review-stars"></i>
              <% end %>
              <% (5 - @review_average).times do %>
                <i class="far fa-star"></i>
              <% end %>
              )
          </h4>

          <div id="reviews">
            <% @garage.bookings.each do |booking| %>
              <% booking.reviews.each do |review| %>
                <div class="review">
                  <p><%= review.content %></p>
                  <div class="reviewer-and-stars">
                    <div id="review-rating">
                      <% review.rating.times do %>
                        <i class="fas fa-star review-stars"></i>
                      <% end %>
                      <% (5 - review.rating).times do %>
                        <i class="far fa-star"></i>
                      <% end %>
                    </div>
                    <div class="garage-card-avatar avatar-bordered tag-item" style="background-image: url(<%= cl_image_path review.booking.bike.user.profile_image %>);">
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>


    <div class="col-12 col-md-5 col-lg-4">

      <div class="garage-show-booking">

        <h3>Book a spot for your <i class="fas fa-bicycle"></i></h3>
        <div class="booking-form-prices">
          <div class="garage-show-card">
            <h4>Regular bike:</h4><p><%= @garage.price_regular_bike %> € /month</p>
          </div>
          <div class="garage-show-card">
            <h4>Large bike:</h4><p><%= @garage.price_large_bike %> € /month</p>
          </div>
        </div>
        <% if user_signed_in?%>
          <% if current_user.id == @user.id %>

            <%= simple_form_for [current_user, @garage, @booking], html: {id: :booking_form} do |f| %>
              <% if @booking.errors.any? %>
                <div class="errors-container">
                  <ul>
                    <% @booking.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
              <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"}, label: "Desired start date" %>
              <% if current_user.bikes.exists? %>

                <!-- Check if the TOTAL capacity for the garage is == 0 then user cannot choose a bike-->

                <% if @garage.capacity_left_regular <= 0 && @garage.capacity_left_large <= 0 %>
                  <h4>No spots left <i class="far fa-surprise"></i> Please choose another garage</h4>

                <!-- Check if the large bike capacity is == 0 then user cannot choose a large bike-->

                <% elsif @garage.capacity_left_large <= 0 %>
                  <div id="array_bike_node" data-bikes="<%= current_user.bikes.where(bike_size: "regular").map{|bike|{ id: bike.id, size: bike.bike_size  } }.to_json  %>" > </div>
                  <%= f.input :bike_id, collection: current_user.bikes.where(bike_size: "regular").map{|bike| [bike.name, bike.id] }, input_html: { :class => "selected-type" }, selected: 1  %>
                  <div>
                    <button type="button" class="btn btn-bike" data-toggle="modal" data-target="#exampleModal">
                      Add a new bike
                    </button>
                  </div>
                <!-- Check if the regular bike capacity is == 0 then user cannot choose a regular bike-->
                  <button type="button" id="submit-booking" class="btn btn-booking"> Send booking request </button>

                <% elsif @garage.capacity_left_regular <= 0%>
                  <div id="array_bike_node" data-bikes="<%= current_user.bikes.where(bike_size: "cargo").map{|bike|{ id: bike.id, size: bike.bike_size  } }.to_json  %>" > </div>
                  <%= f.input :bike_id, collection: current_user.bikes.where(bike_size: "cargo").map{|bike| [bike.name, bike.id] }, input_html: { :class => "selected-type" }, selected: 1  %>
                  <div>
                    <button type="button" class="btn btn-bike" data-toggle="modal" data-target="#exampleModal">
                      Add a new bike
                    </button>
                  </div>
                  <button type="button" id="submit-booking" class="btn btn-booking"> Send booking request </button>
                <!-- If both capacity are free user can choose any bike -->
                <% else %>
                  <div id="array_bike_node" data-bikes="<%= current_user.bikes.map{|bike|{ id: bike.id, size: bike.bike_size  } }.to_json  %>" > </div>
                  <%= f.input :bike_id, collection: current_user.bikes.map{|bike| [bike.name, bike.id] }, input_html: { :class => "selected-type" },selected: 1 %>
                  <div>
                    <button type="button" class="btn btn-bike" data-toggle="modal" data-target="#exampleModal">
                      Add a new bike
                    </button>
                  </div>
                  <button type="button" id="submit-booking" class="btn btn-booking"> Send booking request </button>
                <% end %>
                <div class="show-price bike-price"></div>
              <% else %>
                <p class="text-white">Add a bike before selecting a booking:</p>
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                  Create a new bike
                </button>
              <% end %>
            <% end %>
          <% else %>
            <h2>Stop trying to book for another user</h2>
          <% end %>
        <% else %>
          <!-- Dumb form redirecting to new session form -->
            <%= simple_form_for @booking, url: garages_prompt_loggin_user_garage_path do |f| %>
            <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"}, label: "Desired start date", class: "datepicker"%>
            <p class="text-white">Add a bike before selecting a booking:</p>
            <%= link_to "Add a new bike", garages_prompt_loggin_user_garage_path, class: "btn btn-bike" %>
          <% end %>
        <% end %>
      </div>

      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">New Bike</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <% if user_signed_in?%>
              <div class="modal-body">
                <%= simple_form_for [current_user, @bike] do |f| %>
                  <%= hidden_field :garage, :garage_id, value:  @garage.id %>
                  <%= f.input :name %>
                  <%= f.input :bike_size, collection: %w(regular cargo) %>
                  <%= f.input :bike_type, collection: %w(electric non-electric) %>
                  <%= f.button :submit %>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% if user_signed_in? %>
  <%= link_to "", dashboard_home_user_path(current_user), id: "redirection-link", class: "btn_hidden" %>
  <% end %>
</div>

<script>
  const typeSelectInput = document.querySelector('.selected-type');
  const array_bikes = JSON.parse(document.querySelector("#array_bike_node").dataset.bikes)
  console.log(typeof(array_bikes))
  typeSelectInput.addEventListener('change', e => {
    let id = Number(e.target.value)
    let bikesize = array_bikes.find((bike) => { console.log(bike) ;  return bike.id === id  }).size
    let regularBikePrice = <%= @garage.price_regular_bike.to_i %>;
    let largeBikePrice = <%= @garage.price_large_bike.to_i %>;
    let price_to_pay = ""
      if (bikesize === "cargo") {
        price_to_pay = "Your bike price/month: " + largeBikePrice + " €";
      } else if (bikesize === "regular") {
        price_to_pay = "Your bike price/month: " + regularBikePrice + " €";
      } else {
        price_to_pay = "";
      }
    document.querySelector('.bike-price').textContent = price_to_pay;
    });



  const submitBookingButton = document.querySelector('#submit-booking')

  const submitBooking = () => {
      const redirectLink = document.querySelector("#redirection-link")
      let url = `${location.pathname}/bookings`
      let tokenInput = document.querySelector('meta[name="csrf-token"]')
      let init = {
          method: "POST",
          headers: {
            'X-Requested-With': 'XMLHttpRequest',
            'X-CSRF-Token': tokenInput.content,
            'Content-Type': 'application/json',
            'Accept': 'application/json'
          },
          body: JSON.stringify({
            start_date: document.querySelector('.datepicker').value,
            bike_id: document.querySelector('.selected-type').value
          })
      }

      fetch(url, init)
          .then(response => response.json())
          .then(json => {
            if (json.message === 'booking created') {
              swal(json.message, {
              icon: "success",
              button: "Go to Dashboard"
              })
              document.querySelector(".swal-button").addEventListener("click", () =>{
                redirectLink.click()
              })
            } else {
              swal(json.message, {
              icon: "error"
              })
            }
          })
  }

  submitBookingButton.addEventListener("click", submitBooking)

</script>

app/views/garages/show_card.js.erb
const garageCardList = document.getElementById('garage-card-list');

const card = '<%= j render "map_card", garage: @garage %>';
console.log(card)
garageCardList.insertAdjacentHTML('afterbegin', card);