config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#landing'
  get "garages/index", to: "garages#index"
  get "/how_it_works", to: 'pages#how_it_works'
  resources :users, only: [:edit, :update] do
    resources :bikes, only: [:create, :new]
    member do
      get "dashboard/home", to: "users#home"
      get "dashboard/my_account", to: "users#show"
      get "dashboard/my_garages", to: "users#mygarages"
      get "dashboard/my_bookings", to: "users#mybookings"
      get "dashboard/add_review", to: "users#addareview"
      get "bookings/:id/accept", to: "bookings#accept_request", as: "accept"
      get "bookings/:id/reject", to: "bookings#reject_request", as: "reject"
      get "bookings/:id/cancel_request_by_owner", to: "bookings#cancel_request_by_owner", as: "cancel_request_by_owner"
      get "bookings/:id/cancel_request_by_biker", to: "bookings#cancel_request_by_biker", as: "cancel_request_by_biker"
      delete "bookings/:id/delete_request", to: "bookings#destroy", as: "delete_request"
    end
    resources :garages, except: [:index] do
      member do
        get "card", to: "garages#show_card"
        get "garages-prompt-loggin", to: "garages#show_prompt_loggin"
      end
      resources :reviews, only: [:new, :create]
      resources :bookings, only: [:new, :edit, :create, :update, :show] do
        resources :chats, only: [ :new, :create ]
      end
    end
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end
  mount ActionCable.server => "/cable"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  mount_uploader :profile_image, PhotoUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bikes, dependent: :destroy
  has_many :garages, dependent: :destroy
  has_many :biker_bookings, source: :bookings, through: :bikes, dependent: :destroy
  has_many :owner_bookings, source: :bookings, through: :garages, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :first_name, :last_name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:home, :show, :edit, :update, :mygarages, :mybookings, :addareview]

  def home
    @biker_pending_requests = @user.biker_bookings.where(status: %w(pending rejected accepted paid cancelled_by_owner))
    @owner_pending_requests = @user.owner_bookings.where(status: %w(pending rejected accepted paid cancelled_by_biker))
    @income_bookings = @user.owner_bookings.where(status: %w(paid active))
    @paying_bookings = @user.biker_bookings.where(status: %w(paid active))
  end

  def show
  end

  def mygarages
    @garages = @user.garages
  end

  def mybookings
    @owner_bookings = @user.owner_bookings
    @biker_bookings = @user.biker_bookings
  end

  def edit
  end

  def update
    @user.update(user_params)
    if @user.save
      redirect_to user_dashboard_path(current_user)
    else
      render :edit
    end
  end

  def addareview

  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :payment_info, :street, :street_number, :city, :country, :profile_image)
  end
end

app/views/users/_biker-booking-card.html.erb
<div class="card-dashboard shadow">
  <%= link_to user_garage_path(booking.garage.user, booking.garage), class: 'garage-card-link' do %>
    <div class="garage-card-image" style="background-image: url(<%= cl_image_path booking.garage.profile_image %>);">
    </div>
  <% end %>
  <div class="garage-card-info">
    <% owner_name = "#{booking.garage.user.first_name.capitalize} #{booking.garage.user.last_name.capitalize}" %>
    <% if booking.status == 'pending' %>
      <p class="larger-text">You sent a request to rent <strong><%= booking.garage.name %></strong> for your bike <strong><%= booking.bike.name %></strong>.</p>
      <p>Waiting for a response from garage owner <strong><%= owner_name %></strong>...</p>
    <% elsif booking.status == 'rejected' %>
      <p class="larger-text"><strong><%= owner_name %></strong> has rejected your rental request for  their garage.</p>
    <% elsif booking.status == 'accepted' %>
      <p class="larger-text"><strong><%= owner_name %></strong> has accepted your rental request for their garage!</p>
      <p>Contact <strong><%= owner_name %></strong> to arrange the key exchange. Don't forget to pay!</p>
    <% elsif booking.status == 'paid' %>
      <p class="larger-text">Your payment has been accepted!</p>
      <p>Everything is good. You can safe your bike in <strong><%= booking.garage.name %></strong> starting on <strong><%= booking.start_date %></strong>.</p>
    <% elsif booking.status == 'active' %>
      <p class="larger-text">You are currently renting <strong><%= booking.garage.name %></strong> for your bike <strong><%= booking.bike.name %></strong>.</p>
      <p>Garage owner <strong><%= owner_name %></strong> says hi!</p>
    <% elsif booking.status == 'cancelled_by_owner' %>
      <p class="larger-text">Garage owner <strong><%= owner_name %></strong> has cancelled your request</p>
      <p>for garage <strong><%= booking.garage.name %></strong> for your bike <strong><%= booking.bike.name %></strong>.</p>
    <% elsif booking.status == 'done' %>
      <p class="larger-text">Your rental of <strong><%= booking.garage.name %></strong> for your bike <strong><%= booking.bike.name %></strong> ended on <strong><%= booking.end_date %></strong>.</p>
    <% else %>
      <p class="larger-text"></p>
    <% end %>
    <p><%= booking.garage.street_number %> <%= booking.garage.street_address %>, <%= booking.garage.city %></p>
  </div>
  <div class="top-right">
    <% if %w(rejected cancelled_by_owner cancelled_by_biker done).include? booking.status %>
      <% if booking.status.include? "cancelled_by_owner" %>
        <p class="tag tag-item red-tag">cancelled by owner</p>
      <% elsif booking.status.include? "cancelled_by_biker" %>
        <p class="tag tag-item red-tag">cancelled by biker</p>
      <% else %>
        <p class="tag tag-item red-tag"><%= booking.status %></p>
      <% end %>
    <% elsif booking.status == "pending" %>
      <p class="tag tag-item yellow-tag">pending</p>
    <% else %>
      <p class="tag tag-item"><%= booking.status %></p>
    <% end %>
    <p class='tag tag-item blue-tag'>€<%= booking.price %>/month</p>
    <% unless booking.bike.bike_image.blank? %>
      <div class="garage-card-avatar avatar-bordered tag-item" style="background-image: url(<%= cl_image_path booking.bike.bike_image %>);"></div>
    <% end %>
    <% unless booking.garage.user.profile_image.blank? %>
      <div class="garage-card-avatar avatar-bordered tag-item" style="background-image: url(<%= cl_image_path booking.garage.user.profile_image %>);"></div>
    <% end %>
  </div>
  <div class="bottom-right buttons-container">
    <% if %w(pending accepted).include? booking.status %>
     <%= form_tag orders_path do %>
       <%= hidden_field_tag 'booking_id', booking.id %>
       <%= submit_tag 'enter payment', class: 'btn-flat blue-tag' %>
     <% end %>
    <% end %>
    <% if %w(pending accepted paid active).include? booking.status %>
      <%= link_to "cancel", cancel_request_by_biker_user_path(@user, booking), class: 'btn-flat red' %>
    <% end %>
    <% if %w(cancelled_by_owner cancelled_by_biker rejected done).include? booking.status %>
      <%= link_to "hide", delete_request_user_path(@user, booking), :method => :delete, class: 'btn-flat red' %>
    <% end %>
    <%= link_to "contact owner", user_garage_booking_path(current_user, booking.garage, booking), class: 'btn-flat' %>
  </div>
</div>

app/views/users/_form.html.erb
<div class="row justify-content-center">
  <div class="col-12 col-sm-8 col-md-6 custom-form">

    <h2>Edit your profile:</h2>

    <%= simple_form_for(current_user) do |f| %>
      <%= f.input :first_name,
                  required: true,
                  autofocus: true %>
      <%= f.input :last_name,
                  required: true %>
      <%= f.input :email,
                  required: true,
                  input_html: { autocomplete: "email" }%>
      <%= f.input :password,
                  required: true,
                  hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                  input_html: { autocomplete: "new-password" } %>
      <%= f.input :password_confirmation,
                  required: true,
                  input_html: { autocomplete: "new-password" } %>
      <%= f.input :street,
                  required: false %>
      <%= f.input :street_number,
                  required: false %>
      <%= f.input :city,
                  required: false %>
      <%= f.select :country,
                  required: false %>
      <%= f.input :profile_image %>
      <%= f.input :profile_image_cache, as: :hidden %>
      <%= f.button :submit, class: 'btn btn-flat' %>
    <% end %>

  </div>
</div>

app/views/users/_my-garages-card-subcard.html.erb
 <div class="bike-booking-card">
  <% biker_name = "#{booking.bike.user.first_name.capitalize} #{booking.bike.user.last_name.capitalize}" %>
  <%= cl_image_tag(booking.bike.user.profile_image, width: 40, height: 40, crop: :fill, :class => "avatar-bordered") %>
  <%= cl_image_tag(booking.bike.bike_image, width: 40, height: 40, crop: :fill, :class => "avatar-bordered") %>
  <div class="bike-booking-card-info">
    <% if booking.status == 'pending' %>
      <p><strong><%= biker_name %></strong> wants to his bike <%= booking.bike.name %>.</p>
    <% elsif booking.status == 'rejected' %>
      <p class="larger-text">You have rejected <strong><%= biker_name %></strong>'s request.</p>
    <% elsif booking.status == 'accepted' %>
      <p class="larger-text">You have accepted <strong><%= biker_name %></strong>'s request. Waiting for payment.</p>
    <% elsif booking.status == 'paid' %>
      <p class="larger-text"><strong><%= biker_name %></strong>'s rental starts on <strong><%= booking.start_date %></strong>.</p>
    <% elsif booking.status == 'active' %>
      <p class="larger-text"><strong><%= biker_name %></strong> safes his bike <strong><%= booking.bike.name %></strong>.</p>
     <% elsif booking.status == 'cancelled_by_biker' %>
      <p class="larger-text">Biker <strong><%= biker_name %></strong> has cancelled the rental agreement.</p>
    <% elsif booking.status == 'done' %>
      <p class="larger-text"><strong><%= biker_name %></strong>'s rental ended on <strong><%= booking.end_date %></strong>.</p>
    <% else %>
      <p class="larger-text">error</p>
    <% end %>
    <div>
      <p class='tag'><%= booking.status %></p>
    </div>
    <div>
      <p class='tag blue-tag'>€<%= booking.price %>/month</p>
    </div>
  </div>
  <div class="buttons-container">
    <% if booking.status == 'pending'%>
      <%= link_to "accept", accept_user_path(@user, booking), class: 'btn-flat' %>
      <%= link_to "reject", reject_user_path(@user, booking), class: 'btn-flat red' %>
    <% end %>
    <% if %w(accepted paid active).include? booking.status %>
      <%= link_to "cancel", cancel_request_by_owner_user_path(@user, booking), class: 'btn-flat red' %>
    <% end %>
    <% if %w(cancelled_by_owner cancelled_by_biker rejected done).include? booking.status %>
      <%= link_to "remove", delete_request_user_path(@user, booking), :method => :delete, class: 'btn-flat red' %>
    <% end %>
    <%= link_to "contact biker", user_garage_booking_path(current_user, booking.garage, booking), class: 'btn-flat' %>
  </div>
</div>

app/views/users/_my-garages-card.html.erb
<div class="garage-card-dashboard shadow">
  <div class="top-content">
    <%= link_to user_garage_path(garage.user, garage), class: 'garage-card-link' do %>
      <div class="garage-card-image" style="background-image: url(<%= cl_image_path garage.profile_image %>);"></div>
    <% end %>
    <div class="garage-card-info">
      <h5><%= garage.name %></h5>
      <p><%= garage.street_address %> <%= garage.street_number %>, <%= garage.city %></p>
      <p>Capacity: <%= garage.capacity_reg_bikes %> regular | <%= garage.capacity_large_bikes %> large</p>
      <div class="top-right">
        <div class="buttons-container">
          <%= link_to "garage page", user_garage_path(current_user, garage), class: 'btn-flat' %>
          <%= link_to "edit", edit_user_garage_path(current_user, garage), class: 'btn-flat' %>
          <%= link_to "delete", user_garage_path(current_user, garage), method: :delete, class: 'btn-flat red' %>
        </div>
        <% garage_bookings = [] %>
        <% garage.bookings.where(status: 'active').each do |booking|  %>
          <% garage_bookings << booking.price %>
        <% end %>
        <p class='tag blue-tag'>monthly income: €<%= garage_bookings.sum %></p>
      </div>
    </div>
  </div>
  <div class="wrap-collabsible">
    <input id="collapsible-<%=garage.id %>" class="toggle" type="checkbox">
    <label for="collapsible-<%=garage.id %>" class="lbl-toggle expand">expand to show bookings </label>
    <div class="collapsible-content">
      <div class="content-inner">
        <% if (pending_requests = garage.bookings.where(status: %w(pending rejected accepted paid cancelled_by_owner))).any? %>
          <h5>Pending requests</h5>
          <% pending_requests.each do |booking| %>
            <%= render 'my-garages-card-subcard', booking: booking %>
          <% end %>
        <% end %>
        <% if (active_requests = garage.bookings.where(status: "active")).any? %>
          <h5>Active requests</h5>
          <% active_requests.each do |booking| %>
            <%= render 'my-garages-card-subcard', booking: booking %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/_owner-booking-card.html.erb
<div class="card-dashboard shadow">
  <%= link_to user_garage_path(booking.garage.user, booking.garage), class: 'garage-card-link' do %>
    <div class="garage-card-image" style="background-image: url(<%= cl_image_path booking.garage.profile_image %>);">
    </div>
  <% end %>
  <div class="garage-card-info">
    <% biker_name = "#{booking.bike.user.first_name.capitalize} #{booking.bike.user.last_name.capitalize}" %>
    <% if booking.status == 'pending' %>
      <p class="larger-text"><strong><%= biker_name %></strong> sent you a request to rent <strong><%= booking.garage.name %></strong>.</p>
      <p><strong><%= biker_name %></strong> wants to safe their <strong><%= booking.bike.bike_size %> <%= booking.bike.bike_type %></strong> starting from <strong><%= booking.start_date %></strong>.</p>
    <% elsif booking.status == 'rejected' %>
      <p class="larger-text">You have rejected <strong><%= biker_name %></strong>'s request to rent your garage.</p>
    <% elsif booking.status == 'accepted' %>
      <p class="larger-text">You have accepted <strong><%= biker_name %></strong>'s request to rent your garage.</p>
      <p>We are watiting for <strong><%= booking.garage.user.first_name.capitalize %> <%= booking.garage.user.last_name.capitalize %></strong> to process their payment information.</p>
    <% elsif booking.status == 'paid' %>
      <p class="larger-text"><strong><%= biker_name %></strong>'s payment information has been processed!</p>
      <p>You can now arrange the key exchange with <strong><%= biker_name %></strong> through our chatbox!</p>
      <p>The rental starts on <strong><%= booking.start_date %></strong></p>
    <% elsif booking.status == 'active' %>
      <p class="larger-text"><strong><%= biker_name %></strong> is currently renting your garage</p>
      <p>for their <strong><%= booking.bike.name %></strong>.
    <% elsif booking.status == 'cancelled_by_biker' %>
      <p class="larger-text">Biker <strong><%= biker_name %></strong> has cancelled the agreement</p>
      <p>for garage <strong><%= booking.garage.name %></strong>.</p>
    <% elsif booking.status == 'done' %>
      <p class="larger-text"><strong><%= biker_name %></strong>'s rental of <strong><%= booking.garage.name %></strong> for their bike <strong><%= booking.bike.name %></strong> ended on <strong><%= booking.end_date %></strong>.</p>
    <% else %>
      <p class="larger-text"></p>
    <% end %>
    <p><%= booking.garage.street_number %> <%= booking.garage.street_address %>, <%= booking.garage.city %></p>
  </div>
  <div class="top-right">
    <% if %w(rejected cancelled_by_owner cancelled_by_biker done).include? booking.status %>
      <% if booking.status.include? "cancelled_by_owner" %>
        <p class="tag tag-item red-tag">cancelled by owner</p>
      <% elsif booking.status.include? "cancelled_by_biker" %>
        <p class="tag tag-item red-tag">cancelled by biker</p>
      <% else %>
        <p class="tag tag-item red-tag"><%= booking.status %></p>
      <% end %>
    <% elsif booking.status == "pending" %>
      <p class="tag tag-item yellow-tag">pending</p>
    <% else %>
      <p class="tag tag-item"><%= booking.status %></p>
    <% end %>
    <p class='tag tag-item blue-tag'>€<%= booking.price %>/month</p>
    <% unless booking.bike.bike_image.blank? %>
      <div class="garage-card-avatar avatar-bordered tag-item" style="background-image: url(<%= cl_image_path booking.bike.bike_image %>);"></div>
    <% end %>
    <% unless booking.bike.user.profile_image.blank? %>
      <div class="garage-card-avatar avatar-bordered tag-item" style="background-image: url(<%= cl_image_path booking.bike.user.profile_image %>);"></div>
    <% end %>
  </div>
  <div class="bottom-right buttons-container">
    <% if booking.status == 'pending'%>
      <%= link_to "accept", accept_user_path(@user, booking), class: 'btn-flat' %>
      <%= link_to "reject", reject_user_path(@user, booking), class: 'btn-flat red' %>
    <% end %>
    <% if %w(accepted paid active).include? booking.status %>
      <%= link_to "cancel", cancel_request_by_owner_user_path(@user, booking), class: 'btn-flat red' %>
    <% end %>
    <% if %w(cancelled_by_owner cancelled_by_biker rejected done).include? booking.status %>
      <%= link_to "hide", delete_request_user_path(@user, booking), :method => :delete, class: 'btn-flat red' %>
    <% end %>
    <%= link_to "contact biker", user_garage_booking_path(current_user, booking.garage, booking), class: 'btn-flat' %>
  </div>
</div>

app/views/users/addareview.html.erb
<div>
  <% if current_user.id == @user.id %>
    <div class="dashboard-container" data-index="3">
      <div class="sidebar">
        <%= render 'shared/dashboardsidebar'%>
      </div>
      <div class="dashboard-main">
        <h3 class="dashboard-header">Drop a Review</h3>
        <% @user.bikes.each do |bike| %>
          <% bike.bookings.where(status: ["paid", "done"]).each do |booking| %>
            <% if booking.reviews.blank? %>
              <div class="card-dashboard shadow">
                <%= link_to user_garage_path(booking.garage.user, booking.garage), class: 'garage-card-link' do %>
                  <div class="garage-card-image" style="background-image: url(<%= cl_image_path booking.garage.profile_image %>);">
                  </div>
                <% end %>
                <div class="garage-card-info">
                  <h3><%= link_to booking.garage.name, user_garage_path(current_user, booking.garage_id) %></h3>
                  <p class="py-2">Leasing dates: <%= booking.start_date %> - <%= booking.end_date %></p>
                  <p class="top-right tag tag-item"><%= booking.status %></p>
                  <div>
                    <button type="button" class="btn btn-flat" data-toggle="modal" data-target="#modal-<%=booking.garage.id %>">
                      Review garage
                    </button>
                  </div>
                </div>
            <% end %>
            <div class="modal fade" id="modal-<%=booking.garage.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">DROP A REVIEW</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <%= simple_form_for([current_user, booking.garage, Review.new]) do |f| %>
                      <%= f.input :booking_id, as: :hidden, :input_html => { :value => "#{booking.id}" }  %>
                      <%= f.input :rating %>
                      <%= f.input :content %>
                      <%= f.button :submit, class: "btn btn-flat" %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% else %>
    <h2>Stop trying to break our website.</h2>
    <h2>We're juniors, but we're not <em>that</em> junior.</h2>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= render "form", current_user: @user %>

app/views/users/home.html.erb
<% if current_user.id == @user.id %>
  <div class="dashboard-container" data-index="0">
    <div class="sidebar">
      <%= render 'shared/dashboardsidebar'%>
    </div>
    <!-- Display pending requests as a biker: -->
    <div class="dashboard-main" id="home-display">
      <% if @biker_pending_requests.any? %>
      <h3 class="dashboard-header">Pending rental requests for your bikes:</h3>
        <% @biker_pending_requests.each do |booking| %>
          <%= render 'biker-booking-card', booking: booking %>
        <% end %>
      <% end %>
    <!-- Display received requests as an owner: -->
      <% if @owner_pending_requests.any? %>
      <h3 class="dashboard-header">Pending requests for your garages:</h3>
        <% @owner_pending_requests.each do |booking| %>
          <%= render 'owner-booking-card', booking: booking %>
        <% end %>
      <% end %>

      <!-- Display the income if he is an owner and how much he is paying if he has a bike -->
      <% if @income_bookings.size > 0 || @paying_bookings.size > 0 %>
        <div class="price-container">
          <div id = "return-rents" class="account-card shadowed grow">
              <% bookings = [] %>

              <!-- Owner calculations -->
              <% @income_bookings.each do |booking|  %>
                <% bookings << booking.price %>
              <% end %>
              <% if bookings.sum > 0 %>
            <div id= "owner-income" class="price-card">
                <h1>€<%= bookings.sum %></h1>
                <h3>Monthly income</h3>
            </div>
              <% end %>
              <% bookings = [] %>

              <!-- Biker calculations -->
              <% @paying_bookings.each do |booking|  %>
                <% bookings << booking.price %>
              <% end %>
              <% if bookings.sum > 0 %>
            <div id= "biker-price" class="price-card">
                <h1>€<%= bookings.sum %></h1>
                <h3>Monthly cost</h3>
            </div>
              <% end %>
          </div>
        </div>
      <% end %>
      <div class="account-card shadowed">
        <div class="account-title">
          <h2 class="dashboard-header">Your account information</h2>
          <%= link_to "edit", edit_user_path(@user), class: "btn btn-flat" %>
        </div>
        <div class="account-body">
          <div class="account-pic">
            <% unless @user.profile_image.blank? %>
              <%= cl_image_tag(@user.profile_image, height: 200, width: 200, crop: :fill, class: "avatar-very-large") %>
            <% end %>
          </div>
          <div class="account-info-list">
            <div class="account-info">
              <p class="info">First name:</p>
              <p class="info-content"><%= @user.first_name %></p>
            </div>
            <div class="account-info">
              <p class="info">Last name:</p>
              <p class="info-content"><%= @user.last_name %></p>
            </div>
            <div class="account-info">
              <p class="info">Email:</p>
              <p class="info-content"><%= @user.email %></p>
            </div>
            <div class="account-info">
              <p class="info">Address:</p>
              <p class="info-content"><%= @user.street_number %> <%= @user.street %></p>
            </div>
            <div class="account-info">
              <p class="info">City:</p>
              <p class="info-content"><%= @user.city %></p>
            </div>
            <div class="account-info">
              <p class="info">Country</p>
              <v><%= @user.country %></p>
            </div>
            <div class="account-info">
              <p class="info">Payment info:</p>
              <p class="info-content"><%= @user.payment_info %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <h2>Stop trying to break our website.</h2>
  <h2>We're juniors, but we're not <em>that</em> junior.</h2>
<% end %>

app/views/users/mybookings.html.erb
<% if current_user.id == @user.id %>
  <div class="dashboard-container" data-index="2">

    <div class="sidebar">
      <%= render 'shared/dashboardsidebar'%>
    </div>

    <div class="dashboard-main">
      <div>
        <div>
          <% if @biker_bookings.where(status: %w(pending rejected accepted paid)).any? %>
            <h3 class="dashboard-header">Pending requests:</h3>
            <% @biker_bookings.where(status: %w(pending rejected accepted paid)).each do |booking| %>
              <%= render 'biker-booking-card', booking: booking %>
            <% end %>
          <% end %>
        </div>
        <div>
          <% if @biker_bookings.where(status: "active").any? %>
            <h3 class="dashboard-header">Active rental agreements:</h3>
            <% @biker_bookings.where(status: "active").each do |booking| %>
              <%= render 'biker-booking-card', booking: booking %>
            <% end %>
          <% end %>
        </div>
        <div>
          <% if @biker_bookings.where(status: %w(cancelled_by_owner cancelled_by_biker done)).any? %>
            <h3 class="dashboard-header">Past rental agreements:</h3>
            <% @biker_bookings.where(status: %w(cancelled_by_owner cancelled_by_biker done)).each do |booking| %>
              <%= render 'biker-booking-card', booking: booking %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <h2>Stop trying to break our website.</h2>
  <h2>We're juniors, but we're not <em>that</em> junior.</h2>
<% end %>

app/views/users/mygarages.html.erb
<% if current_user.id == @user.id %>
  <div class="dashboard-container" data-index="1">

    <div class="sidebar">
      <%= render 'shared/dashboardsidebar'%>
    </div>

    <div class="dashboard-main">
      <h3 class="dashboard-header">My garages</h3>

      <% @garages.each do |garage| %>
        <%= render 'my-garages-card', garage: garage %>
      <% end %>

    </div>

  </div>
<% else %>
  <h2>Stop trying to break our website.</h2>
  <h2>We're juniors, but we're not <em>that</em> junior.</h2>
<% end %>

app/views/users/show.html.erb
<% if current_user.id == @user.id %>
  <div class="dashboard-container" data-index="1">

    <div class="sidebar">
      <%= render 'shared/dashboardsidebar'%>
    </div>

    <div class="dashboard-main">

         <div class="card-dashboard">
          <div class="account-headline row">
            <div class="account-body col-12 col-md-7">
              <h2><%= @user.first_name %>'s Profile</h2>
              <div class="account-info">
                <p class="info">First name:</p>
                <p><%= @user.first_name %></p>
              </div>
              <div class="account-info">
                <p class="info">Last name:</p>
                <p><%= @user.last_name %></p>
              </div>
              <div class="account-info">
                <p class="info">Email:</p>
                <p><%= @user.email %></p>
              </div>
              <div class="account-info">
                <p class="info">Address:</p>
                <p><%= @user.street_number %> <%= @user.street %></p>
              </div>
              <div class="account-info">
                <p class="info">City:</p>
                <p><%= @user.city %></p>
              </div>
              <div class="account-info">
                <p class="info">Country</p>
                <p><%= @user.country %></p>
              </div>
              <div class="account-info">
                <p class="info">Payment info:</p>
                <p><%= @user.payment_info %></p>
              </div>

              <%= link_to "Edit my profile", edit_user_path(@user), class: "btn btn-flat" %>
            </div>

          <div class="account-pic col-12 col-md-5">
            <% unless @user.profile_image.blank? %>
              <%= cl_image_tag(@user.profile_image, height: 200, width: 200, crop: :fill, class: "avatar-very-large") %>
            <% end %>
          </div>
        </div>
      </div>

    </div>

  </div>
<% else %>
  <h2>Stop trying to break our website.</h2>
  <h2>We're juniors, but we're not <em>that</em> junior.</h2>
<% end %>