config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#landing'
  get "garages/index", to: "garages#index"
  get "/how_it_works", to: 'pages#how_it_works'
  resources :users, only: [:edit, :update] do
    resources :bikes, only: [:create, :new]
    member do
      get "dashboard/home", to: "users#home"
      get "dashboard/my_account", to: "users#show"
      get "dashboard/my_garages", to: "users#mygarages"
      get "dashboard/my_bookings", to: "users#mybookings"
      get "dashboard/add_review", to: "users#addareview"
      get "bookings/:id/accept", to: "bookings#accept_request", as: "accept"
      get "bookings/:id/reject", to: "bookings#reject_request", as: "reject"
      get "bookings/:id/cancel_request_by_owner", to: "bookings#cancel_request_by_owner", as: "cancel_request_by_owner"
      get "bookings/:id/cancel_request_by_biker", to: "bookings#cancel_request_by_biker", as: "cancel_request_by_biker"
      delete "bookings/:id/delete_request", to: "bookings#destroy", as: "delete_request"
    end
    resources :garages, except: [:index] do
      member do
        get "card", to: "garages#show_card"
        get "garages-prompt-loggin", to: "garages#show_prompt_loggin"
      end
      resources :reviews, only: [:new, :create]
      resources :bookings, only: [:new, :edit, :create, :update, :show] do
        resources :chats, only: [ :new, :create ]
      end
    end
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end
  mount ActionCable.server => "/cable"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_dashboardsidebar.html.erb
<div class="sidebar-body" data-controller="tab">

  <ul class="tabs" id="dashboard-menu">

    <%= link_to dashboard_home_user_path(current_user) do %>
      <li class="sidebar-tab" data-target="tab.bar">
        <i class="fas fa-tachometer-alt"></i>
        <p>Dashboard</p>
      </li>
    <% end %>

    <% if current_user.garages.any? %>
      <%= link_to dashboard_my_garages_user_path(current_user) do %>
        <li class="sidebar-tab" data-target="tab.bar">
          <i class="fas fa-warehouse"></i>
          <p>My Garage(s)</p>
        </li>
      <% end %>
    <% else %>
      <%= link_to dashboard_my_garages_user_path(current_user) do %>
        <li class="sidebar-tab hidden-tab" data-target="tab.bar">
          <i class="fas fa-warehouse"></i>
          <p>My Garage(s)</p>
        </li>
      <% end %>
    <% end %>

    <% bookings_garage = [] %>
    <% bookings_bike = [] %>
    <% current_user.garages.each {|garage| garage.bookings.any? ? bookings_garage << 1 : bookings_garage << 0} %>
    <% current_user.bikes.each {|bike| bike.bookings.any? ? bookings_bike << 1 : bookings_bike << 0} %>
    <% if bookings_garage.sum > 0 || bookings_bike.sum > 0 %>
      <%= link_to dashboard_my_bookings_user_path(current_user) do %>
        <li class="sidebar-tab" data-target="tab.bar">
          <i class="far fa-copy"></i>
          <p>My Rentals</p>
        </li>
      <% end %>
    <% else %>
      <%= link_to dashboard_my_bookings_user_path(current_user) do %>
        <li class="sidebar-tab hidden-tab" data-target="tab.bar">
          <i class="far fa-copy"></i>
          <p>My Rentals</p>
        </li>
      <% end %>
    <% end %>

    <% bookings_done = [] %>

    <% current_user.bikes.each {|bike| bike.bookings.where(status: ["paid", "done"]).any? ? bookings_done << 1 : bookings_done << 0} %>

    <% if bookings_done.sum > 0 %>
      <%= link_to dashboard_add_review_user_path(current_user) do %>
        <li class="sidebar-tab" data-target="tab.bar">
          <i class="far fa-star"></i>
          <p>Add A Review</p>
        </li>
      <% end %>
    <% else %>
      <%= link_to dashboard_add_review_user_path(current_user) do %>
        <li class="sidebar-tab hidden-tab" data-target="tab.bar">
          <i class="far fa-star"></i>
          <p>Add A Review</p>
        </li>
      <% end %>
    <% end %>
  </ul>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-text">
    <ul class="list-inline">
      <li class="list-inline-item"><p><strong>SafeMyBike ©</strong></p></li>
      <li class="list-inline-item"><a href="#"><%= link_to "How it works", how_it_works_path %></a></li>
      <li class="list-inline-item"><a href="#">Support</a></li>
      <li class="list-inline-item"><a href="mailto:f.stevenart@gmail.com">Contact</a></li>
      <li class="list-inline-item"><a href="#">Privacy & terms</a></li>
    </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <h6>SafeMyBike </h6>
    <%=  cl_image_tag('/logo.png') %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
<!--       <li class="nav-item">
        <%= link_to "How it works", how_it_works_path, class: "nav-link" %>
      </li> -->
      <li class="nav-item">
        <%= link_to "Search", garages_index_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Add Your Garage", new_user_garage_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Dashboard", dashboard_home_user_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= cl_image_tag(current_user.profile_image, class: "avatar avatar-bordered dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Search", garages_index_path, class: "dropdown-item" %>
            <%= link_to "Add Your Garage", new_user_garage_path(current_user), class: "dropdown-item" %>
            <%= link_to "Dashboard", dashboard_home_user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Add Your Garage", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>