config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#landing'
  get "garages/index", to: "garages#index"
  get "/how_it_works", to: 'pages#how_it_works'
  resources :users, only: [:edit, :update] do
    resources :bikes, only: [:create, :new]
    member do
      get "dashboard/home", to: "users#home"
      get "dashboard/my_account", to: "users#show"
      get "dashboard/my_garages", to: "users#mygarages"
      get "dashboard/my_bookings", to: "users#mybookings"
      get "dashboard/add_review", to: "users#addareview"
      get "bookings/:id/accept", to: "bookings#accept_request", as: "accept"
      get "bookings/:id/reject", to: "bookings#reject_request", as: "reject"
      get "bookings/:id/cancel_request_by_owner", to: "bookings#cancel_request_by_owner", as: "cancel_request_by_owner"
      get "bookings/:id/cancel_request_by_biker", to: "bookings#cancel_request_by_biker", as: "cancel_request_by_biker"
      delete "bookings/:id/delete_request", to: "bookings#destroy", as: "delete_request"
    end
    resources :garages, except: [:index] do
      member do
        get "card", to: "garages#show_card"
        get "garages-prompt-loggin", to: "garages#show_prompt_loggin"
      end
      resources :reviews, only: [:new, :create]
      resources :bookings, only: [:new, :edit, :create, :update, :show] do
        resources :chats, only: [ :new, :create ]
      end
    end
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end
  mount ActionCable.server => "/cable"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_order

  def new
    @user = current_user
    @booking = @order.booking
    @garage = @order.booking.garage
  end

  def create
    customer = Stripe::Customer.create(
      source: params[:stripeToken],
      email:  params[:stripeEmail]
    )

    charge = Stripe::Charge.create(
      customer:     customer.id,   # You should store this customer id and re-use it.
      amount:       @order.amount_cents,
      description:  "Payment for Booking",
      currency:     @order.amount.currency
    )

    @order.update(payment: charge.to_json, state: 'paid')
    @order.booking.update(status: "paid")
    redirect_to order_path(@order)

  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_order_payment_path(@order)
  end

private

  def set_order
    @order = current_user.orders.where(state: 'pending').find(params[:order_id])
  end
end

app/views/payments/new.html.erb
<div class="form-container">
  <div class="row justify-content-center">
    <div class="col-12 col-sm-8 col-md-6 custom-form">

      <h2>Booking payment</h2>

        <div class="card-dashboard shadow payment-card">
          <%= link_to user_garage_path(@garage.user, @booking.garage), class: 'garage-card-link' do %>
            <div class="garage-card-image" style="background-image: url(<%= cl_image_path @garage.profile_image %>);">
            </div>
          <% end %>

          <div class="garage-card-info payment-form">
            <p class="larger-text">Garage owner: <strong><%= @garage.user.first_name  %> <%= @garage.user.last_name  %></strong> </p>
            <p><%= @garage.street_number  %> <%= @garage.street_address  %></p>

            <%= form_tag order_payments_path(@order) do %>
              <article>
                <label class="amount tag tag-item blue-tag payment-amount">
                  <span>Amount: <%= humanized_money_with_symbol(@order.amount) %></span>
                </label>
              </article>

            <p class="btn btn-flat">Payment disabled for now</p>
<!--           <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-name="SafeMyBike"
            data-email="<%= current_user.email %>"
            data-description="  Booking "
            data-amount="<%= @order.amount_cents %>"
            data-currency="<%= @order.amount.currency %>"></script> -->
        <% end %>
            </div>
          </div>

    </div>
  </div>
</div>